//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parkwhere05.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Bookmark
    {
        [Display(Name = "Bookmark ID")]
        public int BookmarkId { get; set; }

        [Display(Name = "Carpark ID")]
        public Nullable<int> carparkId { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> date { get; set; }

        [Display(Name = "Username")]
        public string username { get; set; }
    
        public virtual Carpark Carpark { get; set; }
    }
}
