//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parkwhere05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carpark
    {
        public int id { get; set; }
        public string carparkNo { get; set; }
        public string address { get; set; }
        public double x_coord { get; set; }
        public double y_coord { get; set; }
        public string carparkType { get; set; }
        public string typeOfparking { get; set; }
        public string shortTermparking { get; set; }
        public string freeParking { get; set; }
        public string nightParking { get; set; }
        public string parkAndrideScheme { get; set; }
        public string adhocParking { get; set; }
    }
}
