//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parkwhere05.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class PetrolStation
    {
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Display(Name = "Station Name")]
        public string petrolStationName { get; set; }

        [Display(Name = "Address")]
        public string address { get; set; }

        [Display(Name = "Latitude")]
        public Nullable<double> latitude { get; set; }

        [Display(Name = "Longitude")]
        public Nullable<double> longitude { get; set; }
    }
}
